name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: my-project-bigquery-api-001

      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/hello-world
          gcloud run deploy hello-world --image gcr.io/$PROJECT_ID/hello-world --platform managed --region us-central1 --allow-unauthenticated
